### PR TITLE
Add metric units option for location weather

### PR DESCRIPTION
**Pull request by nivv**
Add option (?M) which shows m/s instead of km/h. 

Usage:

```bash
weather Göteborg M

```

or 

```bash
weather M
```

### CODE REVIEW

**Comment by nivv** [comment]
skarmklipp 2017-07-31 20 54 34
Example output

**Comment by alexanderepstein** [comment]
I like the idea but the code is written incorrectly at the moment it will only find the weather for your ip location and not a supplied location. I was already using lowercase m to do this for ip location ```weather m``` should work. The following code was rewritten to work with what you are trying to support.
```bash
if [[ $# == "0" ]]; then
  getIPWeather
elif [[ $1 == "help" ]]; then
  usage
elif [[ $1 == "update" ]]; then
  update
elif [[ $1 == "m" ]]; then
  getIPWeather "?m"
elif [[ "${@: -1}" == "m" ]];then
  args=$( echo "${@:1:(($# - 1))}" ?m | sed s/" "//g)
  getLocationWeather $args
elif [[ $1 == "i" ]]; then
  getIPWeather "?u"
elif [[ "${@: -1}" == "i" ]];then
  args=$( echo "${@:1:(($# - 1))}" ?i | sed s/" "//g)
  getLocationWeather $args
else
  getLocationWeather "$@"
fi

```
Commit this, and I will merge since you introduced the idea, thanks for contributing :tada:

**Comment by nivv** [comment]
@alexanderepstein thanks! although it seems that wttr.in differentiates between uppercase `M` and lowercase `m`. Lower case `m` only affects if its `metric` or not while uppercase `M` specifies m/s

related issue on wttr.in https://github.com/chubin/wttr.in/issues/78

https://github.com/chubin/wttr.in/issues/78#issuecomment-289117406

**Comment by alexanderepstein** [comment]
Ah I see, this option can be added by adding two more conditionals, please commit these lines of code like last time:
```bash
if [[ $# == "0" ]]; then
  getIPWeather
elif [[ $1 == "help" ]]; then
  usage
elif [[ $1 == "update" ]]; then
  update
elif [[ $1 == "m" ]]; then
  getIPWeather "?m"
elif [[ "${@: -1}" == "m" ]];then
  args=$( echo "${@:1:(($# - 1))}" ?m | sed s/" "//g)
  getLocationWeather $args
elif [[ $1 == "M" ]]; then
  getIPWeather "?M"
elif [[ "${@: -1}" == "M" ]];then
  args=$( echo "${@:1:(($# - 1))}" ?M | sed s/" "//g)
  getLocationWeather $args
elif [[ $1 == "i" ]]; then
  getIPWeather "?u"
elif [[ "${@: -1}" == "i" ]];then
  args=$( echo "${@:1:(($# - 1))}" ?u | sed s/" "//g)
  getLocationWeather $args
else
  getLocationWeather "$@"
fi

```
The two added conditionals now allow for the user of capital M like ```weather M``` or ```weather Tokyo M```. This merge as a whole will add the ability to use metric or imperial for a certain location, along with adding the feature of getting windspeed in m/s

**Comment by nivv** [comment]
@alexanderepstein commited! :)

**Comment by alexanderepstein** [comment]
:tada:

**Pull request merged**
