### PR TITLE
Update Readme, add BCH

### PR DESCRIPTION
**Pull request by elsesiy**
**Pull Request Label:**
* [ ] Bug
* [ ] New feature
* [X] Enhancement
* [ ] New component
* [X] Typo

**Pull Request Checklist:**
- [X] Have you followed the [guidelines for contributing](https://github.com/alexanderepstein/Bash-Snippets/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same fix or component?
- [X] Have you ran the tests locally with `bats tests`?

-----

Fixed the wrong instructions in Readme and added Bitcoin Cash prior to adding the other functionality we were talking about.

Cheers, Jonas

### CODE REVIEW

**Comment by alexanderepstein** [comment]
Looks good! Thanks for contributing :confetti_ball: Do you still have plans to add the two way conversion and the other features you mentioned in the original PR?

**Comment by elsesiy** [comment]
Yes, I'll eventually find the time ;)

**Comment by elsesiy** [comment]
@alexanderepstein As you realized my idea yourself with [cryptowatch](https://github.com/alexanderepstein/cryptowatch) I take it that I won't need to add this feature to cryptocurrency anymore, right?

**Comment by alexanderepstein** [comment]
@elsesiy If you want to add the features still feel free to and I will definitely merge the PR. If not cryptowatch does slightly suffice but it still cannot handle more than bitcoin, ethereum and litecoin at the moment although if extended it could support those as well.

**Pull request merged**
