### PR TITLE
Fixed stocks api

### PR DESCRIPTION
**Pull request by navanchauhan**
Changed the API to iextrading.com
Now we will be able to use the stocks program again

**Pull Request Label:**
* [ ] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component
* [ ] Typo
* [x] Repair

**Pull Request Checklist:**
- [x] Have you followed the [guidelines for contributing](https://github.com/alexanderepstein/Bash-Snippets/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/alexanderepstein/Bash-Snippets/pulls) for the same fix or component?
- [ ] Have you ran the tests locally with `bats tests`?

-----

### CODE REVIEW

**Comment by navanchauhan** [comment]
Fixes the issue #131

**Comment by navanchauhan** [comment]
I have committed this directly to the master branch because I just replaced the previous API with the current API, that means it is direct consumer ready. Also, no previous feature has been deleted

**Comment by navanchauhan** [comment]
@alexanderepstein What do you think about it ?

**Comment by alexanderepstein** [comment]
Looks perfect, thanks for fixing this :+1:  :tada:

**Pull request merged**
