### PR TITLE
add hl=en to query string

### PR DESCRIPTION
**Pull request by oolongmen**
add hl=en to query string so that response will be display in english and titles can be correctly parse.

### CODE REVIEW

**Comment by alexanderepstein** [comment]
I do see the issue that may occur if a user is from a different country but I am not sure this is the solution.
Try going to https://www.youtube.com/results?search_query=video\?hl=fr and notice how the flag is actually in the search itself, I think you meant to make it more like this https://www.youtube.com/results?search_query=video&hl=fr however if you aren't from france and click that link it will still view the page in english but it will add a little bar at the top allowing you to switch languages. The issue here is that there is no way to force the language without clicking the part of the bar that allows this (something bash-snippets cannot automate)

**Comment by oolongmen** [comment]
Yes, it is intend to pass as an extra argument to query string. From I live, if I do a search query without this argument using curl I will get response in non-english and therefore no Duration and grep will fail. This extra query argument allows the response to be return in english so that grep will not fail. 

do a "curl -A curl -s https://www.youtube.com/results\?search_query\=family" as in ytview script will return me this
[youtube_query_response.txt](https://github.com/alexanderepstein/Bash-Snippets/files/1148618/youtube_query_response.txt)

and doing "curl -A curl -s https://www.youtube.com/results\?search_query\=family\&hl\=en" will return me this
[youtube_query_response_with_hl.txt](https://github.com/alexanderepstein/Bash-Snippets/files/1148630/youtube_query_response_with_hl.txt)

**Comment by alexanderepstein** [comment]
Can you refork the repository and add this change with a new pull request. I changed the command from being ```httpGet link``` to ```httpGet "link"``` which means no escape characters are necessary and this makes the code easier to read. Sorry about that I didn't write ytview and didn't notice the escape usage.

**Comment by oolongmen** [comment]
sure. no problem.

**Pull request closed without merging**
