### PR TITLE
fixed the meme generator script

### LINKED ISSUE #163: Meme generator is not working
**Issue Label:**
* [x] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**
The meme generator does not work due to two bugs I have identified.
1. The website returns a PNG image while the script save it as JPEG, so a user cannot view image until he/she rename it.
2. If we use spaces in text for first or second line it returns an HTML page instead of an PNG image, correct method is using underscore instead of space.

### If its a bug make sure to include this section.
**OS and OS version:**
* [ ] Mac
* [ ] Linux 32 Bit
* [x] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version: Arch Linux

### PR DESCRIPTION
**Pull request by prmsrswt**
The minor bugs listed in #163 were fixed by
1. Using .png extension instead of .jpg
2. Replacing spaces in input line with underscores, using `tr` (fastest method according to [this](https://unix.stackexchange.com/a/162227) ).

**Pull Request Label:**
* [x] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component
* [ ] Typo

**Pull Request Checklist:**
- [x] Have you followed the [guidelines for contributing](https://github.com/alexanderepstein/Bash-Snippets/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/alexanderepstein/Bash-Snippets/pulls) for the same fix or component?
- [x] Have you ran the tests locally with `bats tests`?

-----

### CODE REVIEW

**Comment by prmsrswt** [comment]
fixed #163

**Comment by alexanderepstein** [comment]
Hey, sorry I haven't been able to answer this but before I merge I want to understand why some of  the tests are failing. When I am able to I will take a further look into it

**Comment by prmsrswt** [comment]
I was wondering the same about the tests. Also I appreciate your looking into it.

**Comment by alexanderepstein** [comment]
Not stale still looking into this, been busy with finals

**Pull request closed without merging**
