### PR TITLE
Added a meme generator

### PR DESCRIPTION
**Pull request by navanchauhan**
Fixed using xdg-open and replaced it with httpGet

**Pull Request Label:**
* [ ] Bug
* [ ] New feature
* [ ] Enhancement
* [x] New component
* [ ] Typo

**Pull Request Checklist:**
- [x] Have you followed the [guidelines for contributing](https://github.com/alexanderepstein/Bash-Snippets/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/alexanderepstein/Bash-Snippets/pulls) for the same fix or component?
- [x] Have you ran the tests locally with `bats tests`?

-----
So, I fixed the xdg-open and now the meme generator is compled

### CODE REVIEW

**Comment by navanchauhan** [comment]
Any comments ?

**Comment by alexanderepstein** [comment]
Looks good from a first glance, but wont be able to dive into the script until about this weekend :+1:

**Comment by navanchauhan** [comment]
@alexanderepstein No Problem, Even I'm a student and I know what must be going on

**Comment by alexanderepstein** [comment]
Take a look at what I have changed about the script. I have a comment on the commit message that explains most of it. Can you also close this PR and request to merge this into the dev branch rather than master? Once that is done it should be good to merge

**Pull request closed without merging**
