### PR TITLE
Add shellcheck github action

### PR DESCRIPTION
**Pull request by dadav**
**Pull Request Label:**
* [ ] Bug
* [ ] New feature
* [x] Enhancement
* [ ] New component
* [ ] Typo

**Pull Request Checklist:**
- [x] Have you followed the [guidelines for contributing](https://github.com/alexanderepstein/Bash-Snippets/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/alexanderepstein/Bash-Snippets/pulls) for the same fix or component?
- [x] Have you ran the tests locally with `bats tests`?

-----

I suggest to you the shellcheck github action to lint the code.

### CODE REVIEW

**Comment by alexanderepstein** [comment]
Is this merge all that is required to setup the gh action or will I need to do something else on my end?

**Comment by dadav** [comment]
> Is this merge all that is required to setup the gh action or will I need to do something else on my end?

You juet have to merge :)

**Comment by dadav** [comment]
This is how it will look:
https://github.com/dadav/Bash-Snippets/runs/1195716480

**Comment by alexanderepstein** [comment]
Awesome, this looks great! Thanks for the contribution 👍

**Comment by alexanderepstein** [comment]
So it seems I am missing a whole bunch of shellcheck fixes according to this run 

https://github.com/alexanderepstein/Bash-Snippets/actions/runs/289570133 

Figured with your other merge #222 that there wouldn't be any issues

**Pull request merged**
