### PR TITLE
Reworked installing, updating, uninstalling sections and added guides for aur package

### PR DESCRIPTION
**Pull request by jfrcom**
**Pull Request Label:**
* [ ] Bug
* [ ] New feature
* [x] Enhancement
* [ ] New component
* [ ] Typo

**Pull Request Checklist:**
- [x] Have you followed the [guidelines for contributing](https://github.com/alexanderepstein/Bash-Snippets/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/alexanderepstein/Bash-Snippets/pulls) for the same fix or component?
-----

### CODE REVIEW

**Comment by alexanderepstein** [comment]
I like everything in this except for the changes to the html <details> so that the page would collapse on those sections. Any reason you prefer this structure over that one? The README seems to get a  bit long and harder to find things with the way you have laid it out IMO

**Comment by jfrcom** [comment]
Honestly, I'm not a fan of the collapsing sections. It's just my personal opinion and it is YOUR project. I'll update the readme and add the collapsing back.

**Comment by jfrcom** [comment]
I have now readded the collapsing sections. Feel free to check it out and merge if you're satisfied.

**Comment by alexanderepstein** [comment]
That is fair, I think it just feels make it easier to find what the person is looking for. While it is my project I only keep it that way because I **think** that is what works best but its just an opinion. If the community agrees with you I will happily get rid of the sections, but for now I will keep them. Thanks for making the change and thanks for the contribution of maintaining the AUR :smile:

**Pull request merged**
