### PR TITLE
Create pwned

### PR DESCRIPTION
**Pull request by navanchauhan**
**Pull Request Label:**
* [ ] Bug
* [ ] New feature
* [ ] Enhancement
* [x] New component
* [ ] Typo

**Pull Request Checklist:**
- [x] Have you followed the [guidelines for contributing](https://github.com/alexanderepstein/Bash-Snippets/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/alexanderepstein/Bash-Snippets/pulls) for the same fix or component?
- [ ] Have you ran the tests locally with `bats tests`?

-----
Have I been pwned ?

### CODE REVIEW

**Comment by navanchauhan** [comment]
Ready when you are

**Comment by alexanderepstein** [comment]
Sorry just finished finals for school I will be looking at all pull requests and issues over the course of the next week

**Comment by alexanderepstein** [comment]
Works pretty well would be cool if it could also grab the description of each breach and the breach date, I saw this info from the JSON response but with the current way that you grab all of the breaches this is a slight challenge. This is good enough to merge though, if you ever want to improve it with the aforementioned changes submit another PR and I will most definitely merge that as well.

**Comment by navanchauhan** [comment]
Could you create an issue with the tag of enhancement and comment whatever you want, I’ll try to add it in the script

**Pull request merged**
