### PR TITLE
Youtube-Viewer 

### PR DESCRIPTION
**Pull request by linyostorovovoltos**
I've created a script to display the latest youtube videos of a channel, and allow you to play the videos of that youtube video from the terminal! Please look at this! Sorry if I did anything wrong, I'm a newbie, and if this isn't accepted, please give suggestions! The only thing it requires is sed, awk, and curl, which are all preinstalled on everything.

### CODE REVIEW

**Comment by alexanderepstein** [comment]
Would you be able to get rid of your install.sh, uninstall.sh and the changes you made to my install.sh just want to make sure I handle those aspects of each component so none of that pipeline becomes messed up although it looks like you changed the files correctly I don't want to chance it. 

Would you be able to find a small list of video players that are generally preinstalled on OSX and Linux? If you could I would be able to create a function checking for the existence of one of the video players and when I find one thats installed then use that to play the video. This will prevent the user from having to enter their video player (which I don't think many people know many/any) and will make that cleaner.

Also the line where you display the video titles ```head /home/$USER/.cache/ytchannel/channels/$1/titles.txt -n 20 --quiet``` you need to get rid of the quiet flag for it to actually show the ouput to the user.

On the line where you get the video urls you forgot to replace pewdiepie with ```$1``` so at the moment trying to search something other then pewdiepie and playing the video will still play a pewdiepie video.

Last thing would be to change to tools name to ytview instead of youtube-viewer it is more concise and doesn't have a hyphen

**Comment by linyostorovovoltos** [comment]
The most common preinstalled video players are vlc, mplayer, and mpv. I'm not sure about on Mac, since I don't have it. I'll add the search function, but it'll take a bit. It'll probably be done by tomorrow. Should I reopen the pull request with the newest changes, or what? This is my first time actually doing this.

**Comment by alexanderepstein** [comment]
After making the other changes could you remove the binary file .ytview.swp not really sure what that is doing there

**Comment by linyostorovovoltos** [comment]
I just added the search function and made a rewrite, if you could look and see?

**Comment by alexanderepstein** [comment]
After some tinkering it appears this is causing a lot of trouble on osx to get it working however on linux it was a breeze. I will only allow installation of this tool to linux platforms to keep the user friendliness for all the tools high. This will be added but is still going to be considered a prototype component until I add a few things therefore for now it wont be in the README. 

Thanks for contributing, awesome work. :smile:

**Pull request merged**
