### PR TITLE
small changes

### PR DESCRIPTION
**Pull request by retokromer**
- use `cat` instead of multiple `echo` (easier to maintain)
- alignment
- double spaces
- typo
- uniform use of spaces
- use `${...}` variables
- use `=` inside `[[ ... ]]`

### CODE REVIEW

**Comment by alexanderepstein** [comment]
I like most of the changes but I am curious if there is any reason as to why you would rather do ```if [[ ${variable} = "1" ]]``` vs ```if [[ $variable == "1" ]]``` The latter makes more sense to me as the ```==``` in many languages implies a test of equality where ```=``` in many languages means set the left side to the right side.

**Comment by retokromer** [comment]
If you prefer, I revert to `==`. _De gustibus…_

**Comment by alexanderepstein** [comment]
Thats such a cool phrase. Thanks for reverting back it just helps me read the code although i know it is a preference :smile_cat:

**Comment by alexanderepstein** [comment]
Additionally things like ```${#}``` seems unnecessary. The brackets are used to expand variables but all of the variables you added this to only contain one value so the brackets are redundant.

**Comment by retokromer** [comment]
Done. (I grew up with `=` and `:=` ;-)

**Comment by alexanderepstein** [comment]
Interseting ive used ```:=``` in mathematica to define functions, what did that mean to you?

**Comment by retokromer** [comment]
The same as often today `=`, e.g. `a := a + b` replace `a` by `a` plus` b.

(Mathematically speaking, however, `a = a + b` means `b = 0`.)

**Comment by alexanderepstein** [comment]
Cool I haven't seen that, I think I am going to change all the usage functions to use ```cat``` and ```EOF``` like you did, it becomes way more readable.

**Comment by retokromer** [comment]
_De gustibus…_ I personally prefer always `${...}`, because I can parse it easier when needed.

**Comment by retokromer** [comment]
BTW: it’s a funny script!

**Pull request merged**
