### PR TITLE
Added a bash component for Have I been Pwned

### PR DESCRIPTION
**Pull request by navanchauhan**
Port of my pwned program
Closing Issue #144 
**Pull Request Label:**
* [ ] Bug
* [ ] New feature
* [ ] Enhancement
* [x] New component
* [ ] Typo

**Pull Request Checklist:**
- [x] Have you followed the [guidelines for contributing](https://github.com/alexanderepstein/Bash-Snippets/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/alexanderepstein/Bash-Snippets/pulls) for the same fix or component?
- [ ] Have you ran the tests locally with `bats tests`?

-----

### CODE REVIEW

**Comment by navanchauhan** [comment]
It has been 11 days, and no update

**Comment by alexanderepstein** [comment]
Sorry super busy with final projects for school at the moment, might have a chance to look at these over thanksgiving break

**Comment by alexanderepstein** [comment]
Could you have this script check for the last 3-5 places you have been breached. I think just having the last place isn't as useful as this script could be (would be even better if it generated a list of all the places you have been breached)

**Comment by navanchauhan** [comment]
I’ll be able to do it only with the help of jq. I think it’s time to add it as a dependency cause it’s easier than python. Else I’ll only be able to look at it after my exams (around 7-8th December ) I think once jq’s requirement is filled a lot can happen

**Comment by navanchauhan** [comment]
The desired output can be achieved via jq. Look at my repo named pwned

**Comment by alexanderepstein** [comment]
I do agree that python does not make these things easy but it is a huge push of this repo to not have dependencies like that. I think the project as a whole is a lot more attractive when it can be installed and everything just works. Otherwise I would have never bothered to make the httpGet function and would have forced every user to have curl installed. It is very possible to utilize a loop to go through a json response until we hit an error an example of what I am referring to can be found in the cloudup tool: https://github.com/alexanderepstein/Bash-Snippets/blob/master/cloudup/cloudup#L184

**Comment by navanchauhan** [comment]
Alas, the script now shows every breach

**Comment by navanchauhan** [comment]
due to a bug, i'm not able to edit my pull request. therefore closing this and opening a new pr

**Pull request closed without merging**
