### PR TITLE
(feature): Add script to check a sites enabled SSL ciphers

### PR DESCRIPTION
**Pull request by Stretch96**
* Usage

siteciphers <domain>

eg `siteciphers github.com`

Output:

```
ECDHE-RSA-AES256-GCM-SHA384 - YES
ECDHE-ECDSA-AES256-GCM-SHA384 - NO (sslv3 alert handshake failure)
ECDHE-RSA-AES256-SHA384 - YES
ECDHE-ECDSA-AES256-SHA384 - NO (sslv3 alert handshake failure)
ECDHE-RSA-AES256-SHA - YES
ECDHE-ECDSA-AES256-SHA - NO (sslv3 alert handshake failure)
SRP-DSS-AES-256-CBC-SHA - NO (no ciphers available)
SRP-RSA-AES-256-CBC-SHA - NO (no ciphers available)
SRP-AES-256-CBC-SHA - NO (no ciphers available)
[...]
```

### CODE REVIEW

**Comment by alexanderepstein** [comment]
This looks good! Can you explain further what the usage of this is? I don't fully understand how to use the information provided by the tool (what does it mean exactly). If you can answer that for me I will merge and modify this to fit in with the rest of the pipeline. If merged it will most likely be released in a  few days after I have done the modifications, added tests and test it on OSX and linux. If it ends up not working on one of the platforms (which it seems it should work on both) then it will be added to the extras folder rather than the main pipeline.

**Comment by Stretch96** [comment]
It's useful for debugging, to check which ciphers are enabled / disabled for a given https site.

Sometimes ciphers are deemed vulnerable, so when you are changing configuration, this can be used to confirm that the cipher truly is disabled.

Some browsers (For example old versions of IE) don't support some of the newer ciphers, which would be a good example of when a SysAdmin would need a list of currently supported ciphers so that changes can be made.

**Comment by alexanderepstein** [comment]
These are the ciphers responsible for the encryption that takes place on an https site? Additionally is there any reason at the end of the script you have it sleep for a second?

**Comment by Stretch96** [comment]
Yep, it's to stop spamming / overloading sites 😬 

It can put some amount of load on a site to request every cipher in one go

1 request a second mitigates this 👍

**Comment by alexanderepstein** [comment]
That makes a lot of sense, awesome tool merging now...

**Comment by alexanderepstein** [comment]
Did you code this tool? If so I will add you as a contributor, give you credit as the author on the README and in the script itself.

**Comment by Stretch96** [comment]
I had this laying around for over a year now, had to go looking for whether it was mine or someone elses 😂 

Turns out it is mostly from the Stack Exchange network (Super user) - https://superuser.com/questions/109213/how-do-i-list-the-ssl-tls-cipher-suites-a-particular-website-offers

I've just modified it slightly to take arguments and change the way it outputs the info, so I couldn't take credit for it. Think having the author as https://superuser.com/users/21867/indiv should be good enough 👍 (Stack Exchange answers are under the CC license)

**Pull request merged**
