### PR TITLE
Outthentic tests for bash-snippets tools

### PR DESCRIPTION
**Pull request by melezhik**
Hi @alexanderepstein , I've dropped some [Outthentic](https://github.com/melezhik/outthentic) tests for some bash-snippets tools.  You can see test report here - https://travis-ci.org/melezhik/Bash-Snippets/builds/256839786

### CODE REVIEW

**Comment by alexanderepstein** [comment]
What is different about these tests than the existing ones?

**Comment by melezhik** [comment]
Hi! In short Outthentic gives you much more flexibility in comparison with bats, for example you can use regexps in your checks or check for the block of text ( lines go by line ) or checks in ranges, and moreover you may write your tests in Perl, Python, Ruby, Bash, not Bash only as  with bats. 

Also Outthentic tests are configurable with many formats like Json or YAML

More explanation could be found here - https://github.com/melezhik/outthentic/blob/master/check-files-syntax.md

**Comment by melezhik** [comment]
Probably this post might be also useful - https://sparrowdo.wordpress.com/2017/02/09/outthentic-quick-way-to-develop-user-scenarios/

**Comment by melezhik** [comment]
> The other tests also cover every tool thats part of the main pipeline while this only covers 4 tools.

Of cource this is only an _example_, just to show his it might be,  it's quite easy to add tests for other tools, moreover if you look at the Travis reports these tests also check functionality that bats ones  do not, for example p, running tools with some parametrs and checking the output, like, for example  currency tool ( see example1 and example2  when usd gets converted to rub , 2 cases ) and cheat ( an example with "cheat lua hello" ). The advantage of Outthentic is one can write pretty complex checks using regexps and "continues sequence checks" ( see https://github.com/melezhik/outthentic-dsl#text-blocks ) and other ones .
Right now I can see that bats tests check only that tool's help info is correct ( indeed only "string is included" check ), while with Outthentic you can test much more.

**Comment by alexanderepstein** [comment]
I have been able to use regex within bats as well, like [this](https://github.com/alexanderepstein/Bash-Snippets/blob/master/tests/cheat.bats#L29) Because of that I have been able to test the functionality of most tools. The only ones I cannot test the functionality of are the tools with prompts as bats does not have a way to simulate keyboard input. Can outthentic do this? I have already written the bats tests, I know bash so tests are very easy to write and it seems unnecessary to switch over unless this can simulate keyboard prompt which is the only thing I cannot do that I need to when testing.

**Comment by melezhik** [comment]
> The only ones I cannot test the functionality of are the tools with prompts as bats does not have a way to simulate keyboard input. Can outthentic do this?

Sure. Here is example -  https://travis-ci.org/melezhik/Bash-Snippets/builds/257715948 ( for the code see my latest commits, the source of tests is here - bash-snippets-interactive-test  ).

**Comment by melezhik** [comment]
If you like bash-snippets-interactive-test sparrow plugin ( https://sparrowhub.org/info/bash-snippets-interactive-test ) we can leave it and remove `./outthentic-test`, eventually I may add new tests for other tools require interactive prompt  to existed bash-snippets-interactive-test plugin. Please let me know what do you think. Thanks

**Comment by alexanderepstein** [comment]
I like the interactive tests a lot! It's awesome how versatile all these testing frameworks you created are I must say! I think for me personally however it would be easier for me to use bats over outthentic for the static tools only since I am already familiar with bash and have them all written. But I would love to add the interactive tests you have created. I will attempt to add tests for all interactive tools (except cloudup because it asks for a password).

**Comment by melezhik** [comment]
> I like the interactive tests a lot! It's awesome how versatile all these testing frameworks you created are I must say! 

Thanks :+1: :smile: 

> I think for me personally however it would be easier for me to use bats over outthentic for the static tools only since I am already familiar with bash and have them all written. But I would love to add the interactive tests you have created. I will attempt to add tests for all interactive tools (except cloudup because it asks for a password).


No worries. I have removed `./outthentic-test` and only left `bash-snippets-interactive-test/` - the source code of bash-snippets-interactive-test plugin, is it ok?

**Comment by alexanderepstein** [comment]
Looks perfect to me! Can you explain why the travis C.I build is erroring out? Possibly just try restarting it because it doesn't seem like anything you did should have caused this since it does get to running the bats tests.

**Comment by melezhik** [comment]
Yeah, for some reasons bats tests starts hang after the interactive sparrow check is done, I will try to troubleshoot later.

**Comment by melezhik** [comment]
Weird ... I have commented sparrow lines at all, but `bat tests` still hangs ... - https://travis-ci.org/melezhik/Bash-Snippets/builds/258477175 , have you tried to run Travis tests on your code?

PS guessing - cheat tests implies http connection to `http://cheat.sh` , maybe Travis has network issues when dealing with `http://cheat.sh` resource?

**Comment by alexanderepstein** [comment]
hmm I have been running these tests for a while now with no issue like [this](https://travis-ci.org/alexanderepstein/Bash-Snippets/builds/258427768). I definitely didn't add/need a curl call to/in the travis.yml

**Comment by alexanderepstein** [comment]
It seems like they are stalled builds for some reason, still not sure why though.

**Comment by retokromer** [comment]
The result of the test is positive.

**Comment by melezhik** [comment]
Ok, I juts merged in changes from upstream ( https://github.com/alexanderepstein/Bash-Snippets  ) to avoid any discrepancy, let see if it helps to pass the Travis tests ...

**Comment by melezhik** [comment]
Yay, I see it goes! :smile: - https://travis-ci.org/melezhik/Bash-Snippets/builds/258582824 ,  I probably forked from  the "bad" revision where the  `bats tests` hang ...

**Comment by alexanderepstein** [comment]
Awesome! I expect it to fail the bats taste test. This just seems to be commonplace amongst pull requests until they are merged but all other tests should work

**Comment by alexanderepstein** [comment]
Every other test except for taste passed when you committed with the message [stale file](https://travis-ci.org/melezhik/Bash-Snippets/builds/258585222?utm_source=github_status&utm_medium=notification)

**Comment by melezhik** [comment]
upsss, it hangs again ... even after merge , weird ... - https://travis-ci.org/melezhik/Bash-Snippets/builds/258589276 , but now it succeeds to pass at least some tests ... I will continue troubleshooting tomorrow ...

**Comment by melezhik** [comment]
I was wrong it finally finished - https://travis-ci.org/melezhik/Bash-Snippets/builds/258589276

**Comment by alexanderepstein** [comment]
It seems they all work even when you ahve the sparrow tests uncommented, uncomment the sparrow tests one more time, what i expect to happen is your sparrow tests will run then my bats tests will run they **will** fail when trying to test the taste tool. All pull requests have this issue for some reason, but it goes away once I merge the request.

**Comment by melezhik** [comment]
ok. here is the last build - https://travis-ci.org/melezhik/Bash-Snippets/builds/258592516

**Comment by melezhik** [comment]
ok, now ALL tests went :smile: ( yeah, mostly passed , except `taste` tool )
BTW `siteciphers tool` bash test is pretty time consuming ...

**Comment by alexanderepstein** [comment]
Awesome looks ready to merge :tada: 

Had to do it to em

Yeah the siteciphers tool does take a while to perform one of tests (it goes through a multitude of ciphers and has a builtin delay of one second to make sure you don't overload the server with requests so it takes a while).

**Comment by alexanderepstein** [comment]
Thanks for your contribution! All tests passed once it was merged :smile:

**Comment by melezhik** [comment]
Yeah, good to hear that after all we succeed !

**Pull request merged**
