### PR TITLE
generate Sparrow wrappers for BashSnippets scripts

### PR DESCRIPTION
**Pull request by melezhik**
Hi! I have already uploaded the plugins to SPH and it seems they work fine, here is PR with the plugins' source code.

### CODE REVIEW

**Comment by melezhik** [comment]
Not sure why, but bats tests fail on `taste` tool:

```
not ok 51 Check for latest version of bash-snippets on update

# (in test file tests/taste.bats, line 11)

#   `[ "$status" -eq 0 ]' failed

not ok 52 The -h option should print usage

# (in test file tests/taste.bats, line 17)

#   `[ "$status" -eq 0 ]' failed

not ok 53 Testing short recommendations

# (in test file tests/taste.bats, line 23)

#   `[ "$status" -eq 0 ]' failed

not ok 54 Testing long recommendations

# (in test file tests/taste.bats, line 33)

#   `[ "$status" -eq 0 ]' failed

not ok 55 Testing search on item

# (in test file tests/taste.bats, line 40)

#   `[ "$status" -eq 0 ]' failed

not ok 56 No arguments prints usage instructions

# (in test file tests/taste.bats, line 47)

#   `[ "$status" -eq 0 ]' failed

not ok 57 Get the tools version with -v

# (in test file tests/taste.bats, line 53)

#   `[ "$status" -eq 0 ]' failed
```

However I have not touched it at all ...

**Comment by alexanderepstein** [comment]
Not sure why that test is failing either. I can always look into fixing that later however my only problem is the readme that is added to folder of each tool. The problem is i have a readme on the main page that describes installation update and uninstallation instructions. However if someone went to review the code of a specific tool they would be met with your readme which provides new instrucitons on how to install it. I think it would make more sense just to integrate the sparrow hub install uninstall and update to the original readme on the homepage letting the user know of all the possible option 
1). Manual install through github
2). Sparrowhub install
3). Homebrew install

**Comment by melezhik** [comment]
Ok, I see. Like an idea, we can avoid any confusion if I rename sparrows README.md files to something like sparrow.md , I could adapt sparrow to deal with these new name. What do you think?

**Comment by melezhik** [comment]
Last 2 commits renamed README.md to sparrow.md and patched sparrow.json files

**Comment by alexanderepstein** [comment]
Adding this now but a new tool ```siteciphers``` has been added

**Comment by melezhik** [comment]
Thanks. ))) No worries. I will add it later.

**Pull request merged**
