### PR TITLE
Sparrow plguin for the stocks script

### PR DESCRIPTION
**Pull request by melezhik**
Based on #27

This is how it could be. I have not touched any of your data as you can see, and it seems that going this way we may install/upgrade by  either `stock -u` or  `sparrow plg install stock` (_irrespectively_) and as you see sparrow only cares about `stocks` script changes and provides kinda adapter ( wrapper ) to run the script as sparrow plugin. As long as this is true we are safe. 

This is how one can upload new version of stuck to SparrowHub

```
$ cd stocks/
$ nano sparrowfile.json # bump version
$ sparrow plg upload
```

A have released the plugin to SparrowHub so you can take it for a spin - https://sparrowhub.org/info/stocks

### CODE REVIEW

**Comment by alexanderepstein** [comment]
I am completely cool with the added files especially if it doesn't get rid of my current install/uninstall and update pipeline and if anything just adds another option. If that is the case (which is what it seems like) you can go ahead and do this to all of the scripts you want to add to sparrowhub and add all the necessary files to repo. Then create a single pull request to add all of the files to repo (I don't want this addition coming in as 11 different pull requests). I will merge the request and add additional instructions to the readme for installing through  sparrowhub rather than through git cloning if the user so chooses.

**Comment by melezhik** [comment]
Cool, it seems we are on the same page. ))) the only thing we need to discuss _who_ is going to upload the new versions of plugins ( it might be automated by the way ) once the scripts are changed ?  Probably me as plugin maintainer ? Or if you want to I can delegate this operation to you ( as the scripts author ) , you only need to create an account at sparrowhub in this case.

**Comment by alexanderepstein** [comment]
It would be awesome if it is automated! If not I would ask if you could do it just so it doesn't throw any extra work my way that has to do with installing and updating, since i have my pipeline all set I'm trying to spend most of my time working on the scripts themselves.

**Comment by melezhik** [comment]
Sure, I think I can do it on my own. Anyway we still  need to figure out how I know that a given script is updated and so I can upload the related plugin to SparrowHub? The rough approach is  just to poll your repository for changes, is it a good scenario? Have you tried a git tags to cut your release ? If so I might  rely on tags existence, but it's just an idea ...

**Comment by alexanderepstein** [comment]
I do everything through github releases and tags (this is the crux of my update pipeline) to get the latest release as a version number I already have some code in bash to do just that.

```bash
## This function determines which http get tool the system has installed and returns an error if there isnt one
getConfiguredClient()
{
  if  command -v curl &>/dev/null ; then
    configuredClient="curl"
  elif command -v wget &>/dev/null ; then
    configuredClient="wget"
  elif command -v fetch &>/dev/null ; then
    configuredClient="fetch"
  else
    echo "Error: This tool reqires either curl, wget, or fetch to be installed."
    return 1
  fi

}

## Allows to call the users configured client without if statements everywhere
httpGet()
{
  case "$configuredClient" in
    curl) curl -A curl -s "$@";;
    wget) wget -qO- "$@";;
    fetch) fetch -o "...";;
  esac
}

getConfiguredClient || exit 1
latestVersion=$(httpGet https://api.github.com/repos/alexanderepstein/Bash-Snippets/tags | grep -Eo '"name":.*?[^\\]",'| head -1 | grep -Eo "[0-9.]+" ) #always grabs the tag without the v option

```

**Comment by melezhik** [comment]
Ok, this will be very helpful. Let's close this request and I will create the new one (to cover all the scripts ) very soon.

**Pull request closed without merging**
