### PR TITLE
Added requested qrify script

### PR DESCRIPTION
**Pull request by linyostorovovoltos**
So, I added the script for making qrcodes which I find very useful, so thank you for requesting that! TIL that was possible. Anyways, I wasn't sure what the equivalent of curl -F was for wget and fetch, since I've only ever used curl, so could you make it available for wget and fetch? The update scripts also need to be added. Please review the script I wrote, thanks!

### CODE REVIEW

**Comment by alexanderepstein** [comment]
Just want to see if @chubin would know the equivalent ```wget``` or ```fetch``` flags for ```curl -F-=\<-``` from the man page of curl 
###### -F, --form <name=content>
              (HTTP)  This  lets  curl  emulate a filled-in form in which a user has pressed the submit button. This
              causes curl to POST data using the  Content-Type  multipart/form-data  according  to  RFC  2388.  This
              enables  uploading of binary files etc. To force the 'content' part to be a file, prefix the file name
              with an @ sign. To just get the content part from a file, prefix the file name with the symbol <.  The
              difference  between  @  and  <  is then that @ makes a file get attached in the post as a file upload,
              while the < makes a text field and just get the contents for that text field from a file.

**Comment by alexanderepstein** [comment]
The script itself looks fine however, once I understand how i can at least support fetch since machines that support wget usually have curl preinstalled.

**Comment by linyostorovovoltos** [comment]
Alright, thanks! I'll try to look into it too.

**Comment by linyostorovovoltos** [comment]
@alexanderepstein We can use the other method of doing something like
`curl qrenco.de/$input`

**Comment by alexanderepstein** [comment]
It does work with spaces but they have to me formatted as %20 so curl qrenco.de/hello%20me 
should return with a qr code for ```hello me```

**Comment by alexanderepstein** [comment]
For now this might make the most sense by just disallowing multiline text. Have the user input a string and replace all spaces with %20 and then run a curl on that new string to qrenco and that should do the trick.

**Comment by linyostorovovoltos** [comment]
Alright! @alexanderepstein We can then make it work pretty easily, although I don't know about multiline support. We'll add an option for multiple lines that requires curl.

**Comment by linyostorovovoltos** [comment]
@alexanderepstein I've made the changes, there's no multiline support yet, but we'll change that, maybe make an option to do that that requires curl, but rn I think it's good to go, only needs the update script.

**Comment by alexanderepstein** [comment]
Looks good to me, going to work on it a little bit to ready it for release!

**Comment by chubin** [comment]
I'm not sure that you can do it with fetch (I think you can't), but it works with wget at least.
Use `--post-data `

**Comment by chubin** [comment]
(multiline text is a very useful feature though, I would not disable it)

**Comment by alexanderepstein** [comment]
@chubin it wasn't disabled for no reason and actually in the code the entire framework to having multiline support is setup but if you all the option i echo an error and exit the script because it just wouldn't return new lines. Look at the source and let me know if you see anything inherently wrong. The qrify script will be commented shortly along with cloudup.

**Pull request merged**
